on:
  workflow_dispatch:
  push: { branches: [main, master, release, develop ] }

jobs:
  build-push:
    runs-on: ubuntu-24.04
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: gem install build-labels:0.0.22
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - run: |
          cd docker
          build-labels -n -c docker-compose.yml gitlab set_version to_dockerfiles to_compose | tee bake.yml
          export $(grep -v '^#' .env | xargs)
          export REPOSITORY_OWNER=${{ github.repository_owner}}
          export REGISTRY_HOST=ghcr.io/${REPOSITORY_OWNER,,}/${{ github.event.repository.name }}
          export CI_COMMIT_BRANCH=${{ github.ref_name }}
          docker buildx bake -f bake.yml --push
